const state={networks:[],addresses:[],selected:null,scanTimer:null};
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
async function api(path,options={}){const r=await fetch(path,{headers:{"Content-Type":"application/json"},...options});if(!r.ok){let e;try{e=(await r.json()).error.message}catch{e=`Request failed (${r.status})`}throw new Error(e)}return r.status===204?null:r.json()}
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2400)}
function capacity(cidr){const [_,bits]=cidr.split("/");const n=Number(bits);return cidr.includes(":")?null:Math.max(0,2**(32-n)-2)}
async function load(){const [stats,networks,addresses]=await Promise.all([api("/api/v1/stats"),api("/api/v1/networks"),api("/api/v1/addresses")]);state.networks=networks.items;state.addresses=addresses.items;$("#stat-networks").textContent=stats.networks;$("#stat-addresses").textContent=stats.addresses;$("#stat-discovered").textContent=stats.discovered;const cap=state.networks.reduce((n,x)=>n+(capacity(x.cidr)||0),0);$("#stat-utilization").textContent=cap?`${Math.round(stats.addresses/cap*1000)/10}%`:"—";renderNetworks();if(state.selected){const still=state.networks.find(n=>n.id===state.selected.id);if(still)selectNetwork(still);else state.selected=null}}
function renderNetworks(){const el=$("#network-list");if(!state.networks.length){el.innerHTML='<div class="empty">No networks yet. Add your first address range to get started.</div>';return}el.innerHTML=state.networks.map(n=>{const used=state.addresses.filter(a=>a.network_id===n.id).length,cap=capacity(n.cidr),pct=cap?Math.min(100,used/cap*100):0;return `<article class="network-card ${state.selected?.id===n.id?'selected':''}" data-network="${esc(n.id)}"><h3>${esc(n.name)}</h3><code>${esc(n.cidr)}</code><p>${esc(n.description||"No description")}</p><div class="meter"><span style="width:${pct}%"></span></div><div class="network-meta"><span>${used} tracked</span><span>${cap?`${Math.round(pct*10)/10}% used`:'IPv6'}</span></div></article>`}).join("");$$('[data-network]').forEach(el=>el.onclick=()=>selectNetwork(state.networks.find(n=>n.id===el.dataset.network)))}
function selectNetwork(network){state.selected=network;renderNetworks();$("#addresses-panel").classList.remove("hidden");$("#address-title").textContent=network.name;$("#address-subtitle").textContent=network.cidr;const rows=state.addresses.filter(a=>a.network_id===network.id);$("#address-list").innerHTML=rows.length?rows.map(a=>`<tr><td><code>${esc(a.ip)}</code></td><td>${esc(a.hostname||'—')}</td><td><span class="pill ${esc(a.status)}">${esc(a.status)}</span></td><td><code>${esc(a.mac||'—')}</code></td><td>${a.last_seen_at?new Date(a.last_seen_at).toLocaleString():'—'}</td><td><button class="delete" data-delete="${esc(a.id)}" title="Delete">×</button></td></tr>`).join(""):'<tr><td colspan="6" class="empty">No addresses tracked in this range.</td></tr>';$$('[data-delete]').forEach(b=>b.onclick=()=>deleteAddress(b.dataset.delete))}
async function deleteAddress(id){if(!confirm("Remove this address from IPAM?"))return;try{await api(`/api/v1/addresses/${id}`,{method:"DELETE"});toast("Address removed");await load()}catch(err){toast(err.message)}}
async function deleteNetwork(){if(!state.selected)return;if(!confirm(`Delete network ${state.selected.name}? This is only allowed after its addresses have been removed.`))return;try{await api(`/api/v1/networks/${state.selected.id}`,{method:"DELETE"});state.selected=null;$("#addresses-panel").classList.add("hidden");toast("Network deleted");await load()}catch(err){toast(err.message)}}
$$('[data-open]').forEach(b=>b.onclick=()=>$("#"+b.dataset.open).showModal());$$('[data-close]').forEach(b=>b.onclick=()=>b.closest("dialog").close());
$("#network-form").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,o=Object.fromEntries(new FormData(f));try{await api("/api/v1/networks",{method:"POST",body:JSON.stringify(o)});f.closest("dialog").close();f.reset();toast("Network created");await load()}catch(err){f.querySelector('.form-error').textContent=err.message}};
$("#address-form").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,o=Object.fromEntries(new FormData(f));o.network_id=state.selected.id;try{await api("/api/v1/addresses",{method:"POST",body:JSON.stringify(o)});f.closest("dialog").close();f.reset();toast("Address added");await load()}catch(err){f.querySelector('.form-error').textContent=err.message}};
$("#allocate").onclick=async()=>{try{const a=await api(`/api/v1/networks/${state.selected.id}/allocate`,{method:"POST",body:JSON.stringify({status:"assigned"})});toast(`Allocated ${a.ip}`);await load()}catch(err){toast(err.message)}};
$("#delete-network").onclick=deleteNetwork;
$("#discover").onclick=async()=>{try{const j=await api("/api/v1/discoveries",{method:"POST",body:JSON.stringify({network_id:state.selected.id})});watchScan(j.id)}catch(err){toast(err.message)}};
async function watchScan(id){clearTimeout(state.scanTimer);const bar=$("#scan-status");bar.classList.remove("hidden");const j=await api(`/api/v1/discoveries/${id}`);bar.textContent=`Discovery ${j.status} · ${j.scanned} scanned · ${j.reachable} reachable`;if(j.status==="complete"||j.status==="failed"){await load();if(j.status==="complete")toast("Discovery complete");return}state.scanTimer=setTimeout(()=>watchScan(id),800)}
$("#refresh").onclick=()=>load().catch(e=>toast(e.message));load().catch(e=>toast(e.message));
